### ISSUE TITLE
"Uncaught TypeError: Module._emscripten_futex_wake is not a function" While running

### ISSUE THREAD

**Issue by AdemJensen** [UnrealEngineHTML5/Documentation#14] opened 2020-03-18 01:58 UTC
As shown above, when I finished packing and deployed it on a Linux Apache2 Server, the file will be successfully downloaded on Chrome, but the Engine is unable to boot. It will display a message "Uncaught TypeError: Module._emscripten_futex_wake is not a function" on the screen and error messages towards ".worker.js" file.
Also, Firefox won't even start the download, it saids "LinkError: shared memory is disabled".
I have deployed it to the internet: disk.chorg.top:20080

**Comment by AdemJensen** [comment] 2020-03-18 02:15
I modified the call from Module array to direct function call, and the error changed to :

> Uncaught abort(Assertion failed: target_thread, at: D:\ProgramData\Documents\UnrealEngine\Engine\Platforms\HTML5\Build\emsdk\emsdk-1.39.0\upstream\emscripten\system\lib\pthread\library_pthread.c,466,emscripten_async_queue_call_on_thread). Build with -s ASSERTIONS=1 for more info.

which is more frustrating because I don't know what to do now...

**Comment by AdemJensen** [comment] 2020-03-18 04:33
Also, the "HTML5LaunchHelper.exe" is nowhere to found and I am unable to perform local test without an Apache server.

**Comment by Mosel3y** [comment] 2020-03-18 10:36
@AdemJensen Regarding your last concern, use the command:

`python -m http.server 8000`

See my comment here:
https://github.com/UnrealEngineHTML5/Documentation/issues/13#issuecomment-600170824

Nick is working on getting HTML5LaunchHelper.exe working on Windows, according to his documentation.

**Comment by Mosel3y** [comment] 2020-03-19 02:16
Also, did you have multithreading support enabled when you got that first error? 
Are you on Nick's 4.24 HTML5 fork, or have have you merged it into 4.24.3?

**Comment by AdemJensen** [comment] 2020-03-19 02:26
I have enabled the multithreading support.
And also, it's Nick's 4.24 HTML5 fork, but my project comes from 4.24.3

**Comment by AdemJensen** [comment] 2020-03-20 05:36
I have tried the same thing via Mac, and the packed project have the exact same error as it’s on Windows.
In my opinion, it appears that some where in the generation code, it uses absolute path, which has been displayed on the web page.
Also the problem of integer/float value range stuff appears repeatedly, this problem also appear on both platforms.
Another thing, the “HTMLLaunchHelper.exe” did not appear at the packed project folder, so it still needs to use python to boot.
Also, python command no longer works, you need to use python3 command.

**Comment by Mosel3y** [comment] 2020-03-20 13:06
Ah, yes, I have had that error in 4.24.3 also. 

It seems to be a problem with multithreading. If you disable multithreading, you will get further but I have got another issue after that. 

The futex error seems to be caused in this way perhaps: https://github.com/emscripten-core/emscripten/issues/8446

I think this issue may relate to the patch files in the repo, I don't think they are being properly applied for Python 3, and some of those files relate to multiprocessing. The patch files are also Python 2, it seems. 

I'm not sure though.

Are you able to package and run the FPS example project?

**Comment by AdemJensen** [comment] 2020-03-20 16:32
Well, I haven’t try to pack a sample project yet, but I did tried to change the emsdk’s python version back to 2.7, and all the same.
One thing interesting: On windows the packed project has a size of 600MB, while on Mac packed it’s 120MB, that’s a huge difference......
And also, the packed project won’t work on Safari too... Same as Firefox, won’t start download (I forgot the details because the whole UE4 source code took me 100GB of space out of 1TB...... and I have delete them.)

**Comment by Mosel3y** [comment] 2020-03-20 22:11
It isn't expected to work on Safari to be true. Safari is fairly feature limited. Probably worse than Edge at this stage. 

That is a big difference, do you remember were had you the same target, development/shipping? I have found an increase in build size  on Windows compared to the internal 4,23 package.  But, I haven't enough info yet, it might be related to .paks. The difference wasn't as great as what you describe though.

Hopefully Nick can offer some insight here. I would recommend trying to build a sample project just so we are all on the same page though. It will be difficult to troubleshoot this with your specific use case.

At the moment I am merging Nick's HTML5 platform onto a clean 4.24.3 clone. So I will let you know how that goes, if I get similar errors and how I fix them. They will likely apply for you. Though I think Nick is also working on merging 4.24.3 changes ?

**Comment by AdemJensen** [comment] 2020-03-21 05:35
Alright, I will build a sample project later, appreciate your hard work.
(P.S. Building a HTML5 project is so hard, 500+ files to build, and no cache... Every minor change cost half a hour...

**Comment by AdemJensen** [comment] 2020-03-21 06:36
I have tested the FPS sample map, and it worked, without any error!
So now I assume something in my project is preventing it from running properly. Here is the project’s source code: https://github.com/AdemJensen/Gobang-Game-UE4  (I forgot to post that out the whole time...)
I will find some time to try out which part exactly caused the errors, hopefully will be able to help.

**Comment by AdemJensen** [comment] 2020-03-21 06:51
Out of curiosity, WHY does Epic Games removed the HTML5 support from their engine code?

**Comment by Mosel3y** [comment] 2020-03-22 00:04
I will try to build your project and get back to you, probably in the next day or two.
I'm not sure why they removed support, I guess it isn't something most users are interested in unfortunately. It happens to be crucial to my companies work with Unreal though, so I appreciate Nick's efforts in keeping progress on it.  And hope it continues and more people get involved.

**Comment by AdemJensen** [comment] 2020-03-22 01:47
Well, thanks a lot!
And by looking the number of the stars of UnrealEngineHTML5/UnrealEngine, I think it’s because the need of HTML5 project is just too little?

**Comment by fllyingburritos** [comment] 2020-04-17 00:28
I got it to work if I just set my project to development, not shipping

**Comment by gaborpapp** [comment] 2020-04-21 14:20
I can reproduce this with the FPS sample as well. Packaging with development configuration works, but with shipping I get the error above.

**Comment by bigjcr** [comment] 2020-04-28 20:12
I got a custom project working just fine in Development too, but Shipping throws this error: Module._emscripten_futex_wake is not a function

Currently the Development build is about 232 MB in size, and Shipping is 150, so it would be awesome if Shipping build worked.

I noticed that on the Development build it logs Emscripten configuration: and points to the route of the .emscripten file at \Engine\Intermediate\Build\HTML5 but on Shipping build it appears to be pointing nowhere, not sure if this has anything to do with the problem.

**Comment by Awesumson** [comment] 2020-05-05 20:34
I've been testing a sample project for hours, first it worked fine (and was 600mb), then I fiddled with it and it stopped working. I didn't think it would be shipping causing it so I've spent hours trying to hunt down the problem -.- Building for HTML takes so long too! I hope someone finds a fix soon

**Comment by bigjcr** [comment] 2020-05-05 20:46
I managed to reduce the weight of the final data file by disabling a few checks in Project Settings > Packaging,
those related to exclude editor content when cooking. I also enabled create compressed cooked packages. The final weight is 132mb which is pretty reasonable for the size of my project. 
In the end tho, the quality wasn't so good and antialiasing was impossible to enable without crashing the game, even trying to force it with WebGL by editing the final js files.

So I moved to Unity and got the same project working in one day with antialiasing and other post process effects... Don't take me wrong, I love unreal but WebGL is currently much easier to work with on Unity.

**Comment by Awesumson** [comment] 2020-05-05 20:50
Was that still with a development build? I managed to get the sample project down to about 118mb but I imagine having a development build would make it much higher

**Comment by bigjcr** [comment] 2020-05-05 22:49
Yes, it was a development build, Shipping still does not work.

**Comment by AdemJensen** [comment] 2020-05-06 01:00
Actually I found a strange thing...... The build on my Windows machine does takes 600MB, but on Mac it only took 300MB(Development), works properly. I just don’t know what’s the difference...

**Comment by nickshinpho** [comment] 2020-05-30 17:14
4.24.3 has now been pushed up.

- UnrealEngineHTML5/UnrealEngine/commit/9182b739760c255cf68c1983719a48e7628b33e6

tested on chrome canary and firefox nightly.

be sure to clear your cache when reloading your projects on your browsers.

**Closed by nickshinpho** 2020-05-30 17:14 UTC
Labels: 4.24.3

**Comment by fllyingburritos** [comment] 2020-06-21 10:13
I am still having this problem now.  4.24.3, shipping or development with multi threading enabled and disabled, it does not work.  When in development, the browser freezes on a black screen.
